### PR TITLE
Fix error with axios and proxies

### PR DESCRIPTION
**Pull request by juancsch**
Remove axios dependecy due to this module has an error when the request is made via proxy (https://github.com/axios/axios/issues/4531#issuecomment-1608140085). 

Selenium-standalone has got http client that is better for this job.

`
2024-02-29T22:19:28.010Z - [selenium-standalone] [start] error installing version 4.17.0 selenium STACK: AxiosError: Request failed with status code 501
    at settle (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/selenium-standalone/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/selenium-standalone/node_modules/axios/dist/node/axios.cjs:3066:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/selenium-standalone/node_modules/axios/dist/node/axios.cjs:3877:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getLastChromedriverVersionFromMajor (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/selenium-standalone/lib/compute-download-urls.js:284:20)
    at async computeFsPaths (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/selenium-standalone/lib/compute-fs-paths.js:17:23)
    at async Object.install (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/selenium-standalone/lib/install.js:84:19)
    at async SeleniumStandalonePlugin.start (/home/testrunner/run_test_env/TG-CHROM0-CCHD/sources/itests-orchard/node_modules/@bbva-qe/orchard-selenium-standalone-plugin/lib/index.cjs:124:7)
    at async Promise.all (index 3)
`

### CODE REVIEW

**Comment by christian-bromann** [comment]
@seanpoulter mind taking a look?

**Review by seanpoulter — CHANGES_REQUESTED** [review]
This looks good. Could you please remove the other reference to `axios` in **dependabot.yml** and have a quick look at the failing test?

**Comment by juancsch** [comment]
The errors in CI are strange, i run the tests in my machine (latest ubuntu version) for all node versions, from 12 to 20, and all passed. I put some console in test for debugging this issue in CI, when tests pass i remove it.

**Comment by seanpoulter** [comment]
Thanks for having a look @juancsch. If this fixes your proxy issue let's remove that logging, merge the PR, and cut a release.

I had a look at the failing test. It isn't great. We're trying to check that the files haven't changed in the **.selenium/** directory but it doesn't report **what** changed if the tests fail, or report if new files were added. We can improve that in a follow-up PR.

**Review by seanpoulter — APPROVED** [review]

**Pull request merged**
