### PR TITLE
onlyDriver feature

### PR DESCRIPTION
**Pull request by udarrr**
Hi @christian-bromann  here is new feature onlyDriver it allow to install or start any driver directly without selenium-server (prevented from downloading also)

Ports for drivers by default:
for chromedirver port is 9515
for edgedriver port  is 9515
for firefox port  is 4444

The ports can be changed in onlyDriverArgs

Before each driver execution process killer check port and process name existence

related to https://github.com/webdriverio/selenium-standalone/issues/843

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by udarrr** [comment]
Could we merge it with 9.2.0 ?

**Comment by christian-bromann** [comment]
@udarrr I just added you to the project org, can you check whether you can merge and release now? Let me know if you have any questions.

**Comment by udarrr** [comment]
> @udarrr I just added you to the project org, can you check whether you can merge and release now? Let me know if you have any questions.

Oh. Looks like not, it's still not allowed me. If you don't mind could you merge it by you own now, because i'd like to use the changes asap...and then we could check all the permissions.

**Comment by christian-bromann** [comment]
Sure. Make sure to check your emails and accept the invitation.

**Comment by udarrr** [comment]
> Sure. Make sure to check your emails and accept the invitation.

Oh That's what it was... yes there is a invitation thank you @christian-bromann I do my best! :)

**Pull request merged**
