### PR TITLE
Fix conditional driver loading

### PR DESCRIPTION
**Pull request by eric1234**
This is a follow-up to #660.

The "should start with the given drivers" test was not passing for me. I believe this is because `--detect-drivers` is auto-loading drivers it can find on some peoples system but on my system there are no drivers in the PATH so it causes an error by the JAR file. Either that or it is failing for everybody and the JAR file changed behavior recently to throw an error when no drivers can be found and `--detect-drivers` is enabled.

In #660, I thought `--detect-drivers` only did auto-detection and since we were specifying the path to all drivers it should not be needed. By setting that to false it caused the tests to pass. Unfortunately as @wyhmichael correctly pointed out that option will stop all loading of drivers not just the ones auto-detected. We should be using the `-I` option to indicate what drivers to load.

This PR does 3 things:

* 6503855 reverts the revert of my original work. I wanted to do this because that work had other fixes we want to keep (stdio fixes) as well as I would like the wrong code to initially be in the system so we can update the test suite to detect the problem I created.
* 7f789b3 makes that update to the test suite to detect the problem. Instead of examining the arguments to see what was asked to be loaded it examines the Selenium output to see what was actually loaded. By making this change my wrong code is no longer passing.
* 3fcbe26 wraps this up by removing my wrong code and replacing it with the `-I` arguments that I think make the right code.

Commit messages have a bit more info but hopefully this should work better than my last attempt.

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Another excellent PR, well done 👍

**Comment by bmcfeely** [comment]
Hi @eric1234! I'm still digging in, but I think this change might be preventing safari from opening. I'm still sorting this out, just a heads up. I seeing that when I remove the -I args from the command line, then selenium-standalone will open up a safari session, but with those `-I` args as they are now, selenium-standalone seems to silently do nothing.

**Comment by bmcfeely** [comment]
@christian-bromann @eric1234 Thanks all! I'll get a PR up in the next hour or so.

**Comment by bmcfeely** [comment]
Done! The code comment here may be a little wordy, I can edit if it's too much. 😄  https://github.com/webdriverio/selenium-standalone/pull/675

**Comment by christian-bromann** [comment]
Sweet, thanks for taking a stab at it 👏  Let's continue convo in the PR.

**Pull request merged**
