### PR TITLE
Update compute-download-urls.js

### PR DESCRIPTION
**Pull request by harsha509**
Updating generic URL for all selenium jar downloads

### CODE REVIEW

**Comment by harsha509** [comment]
Fixes https://github.com/webdriverio/selenium-standalone/issues/582

**Comment by christian-bromann** [comment]
@harsha509 it seems like some of the unit tests are failing, can you check?

**Comment by harsha509** [comment]
Hi @christian-bromann ,

Updated tests accordingly !

**Review by christian-bromann — APPROVED** [review]
Thanks a ton 👍

**Pull request merged**
